data:
  name: pdbbind2016
  split:
    train:
      - refined
    val:
      - core
    test:
      - core
  feature_type: pybel # [pybel, rdkit]
  preprocessing_type: processed # [raw, processed]
  use_docking: false
  input_type: 3d
  max_atoms: 2000

model:
  name: conv3d
  params:
    preprocess: true
    num_filters: [64, 128, 256]
    deeper: true
  loss:
    - name: mse
      weight: 1.0
  ckpt_path: ""

train:
  batch_size: 100
  num_workers: 0
  epochs: 200
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [80, 160]
      gamma: 0.1

test:
  batch_size: 10
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
