data:
  split:
    train:
      - [pdbbind2020, train]
      - [pdbbind2020, val]
    val:
      - [pdbbind2020, test]
    test:
      - [pdbbind2020, test]
  input_type: graph

model:
  name: combative
  params:
    hidden_channels: 20
    dim_feedforward: 2048
    dropout: 0.5
    
  loss:
    - name: mse
      weight: 1.0
  ckpt_path: ""

train:
  batch_size: 32
  num_workers: 0
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.0001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 32
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
