data:
  split:
    train:
      - [pdbbind2020, train]
    val:
      - [pdbbind2020, test]
    test:
      - [pdbbind2020, test]
  input_type: graph

model:
  name: egnn
  params:
    in_edge_nf: 1
    distance_cutoff: 5
    n_layers: 4
    residual: true
    attention: true
    normalize: false
    tanh: false
    estlabel: true
    
  loss:
    - name: mse
      weight: 1.0
    - name: bce
      weight: 1.0
  ckpt_path: ""

train:
  batch_size: 32
  num_workers: 8
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 32
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
