data:
  split:
    train:
      - [yellow, train]
    val:
      - [yellow, train]
    test:
      - [yellow, train]
  input_type: graph
  preprocessing_type: processed
  feature_type: pybel
  use_docking: false

model:
  name: egnn
  params:
    in_edge_nf: 1
    distance_cutoff: 5
    n_layers: 6
    residual: True
    attention: True
    normalize: False
    tanh: False
  loss:
    - name: mse
      weight: 1.0
  ckpt_path: ""

train:
  batch_size: 32
  num_workers: 8
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
