data:
  split:
    train:
      - [zika, train]
    val:
      - [zika, valid]
    test:
      - [zika, test]
  input_type: graph
  feature_type: pybel # [pybel, rdkit]
  preprocessing_type: processed # [raw, processed]
  use_docking: false
  max_atoms: 2000
  with_zeros: true
  type: scaffold
  pocket: 6kk4
  poses: 20

model:
  name: egnn
  params:
    in_edge_nf: 1
    distance_cutoff: 5
    n_layers: 4
    residual: True
    attention: True
    normalize: False
    softmax: true
    estlabel: true
    tanh: False
    label_channels: 2
    freeze: true
    
  loss:
    - name: mse
      weight: 1.0
    - name: ce
      weight: 1.0
  ckpt_path: "/p/vast1/ranganath2/fast.tmp/DENV2/EGNN-20240923-163731-899768-mr2i36en/best_model.pth"

train:
  batch_size: 32
  num_workers: 8
  epochs: 100
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.0001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
    - ce
