data:
  split:
    train:
      - [denv2, train]
    val:
      - [denv2, valid]
    test:
      - [denv2, test]
  input_type: graph
  feature_type: pybel # [pybel, rdkit]
  preprocessing_type: processed # [raw, processed]
  use_docking: false
  max_atoms: 2000
  with_zeros: true
  type: random
  pocket: 2fom
  poses: 20

model:
  name: egnn
  params:
    in_edge_nf: 1
    n_layers: 4
    residual: True
    attention: True
    normalize: False
    tanh: False
    softmax: True
    freeze: True
    estlabel: False
    
  loss:
    - name: mse
      weight: 1.0
  ckpt_path: "/p/lustre1/ranganath2/fast.tmp/PDBBIND2020/EGNN-20240819-174309-871564-clrte403/best_model.pth"

train:
  batch_size: 16
  num_workers: 8
  epochs: 100
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.0001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
