data:
  split:
    train:
      - [mpro, train]
    val:
      - [mpro, val]
    test:
      - [gmd, all]
  input_type: ["graph", "point"]
  max_atoms: 2000
  affine: false

model:
  name: fusion
  params:
    attention: true
    freeze: true
  first:
    name: sgcnn
    params:
      covalent_neighbor_threshold: 1.5
      non_covalent_neighbor_threshold: 4.5
      covalent_gather_width: 16
      covalent_k: 2
      non_covalent_gather_width: 12
      non_covalent_k: 2
  second:
    name: pcn
    params:
      num_filters: 2048
      use_feat: false
  loss:
    - name: mse
      weight: 1.0
  ckpt_path: ""
  #ckpt_path: "/usr/workspace/atom/glo_spl/affinity_files/fast2/FUSION_SGCNN+PCN-20230505-004333-un2cjt85-FREEZE_ATTENTION_x10/best_model.pth"

train:
  batch_size: 16
  num_workers: 8
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
