data:
  split:
    train:
      - [mpro, train]
    val:
      - [mpro, val]
    test:
      - [mpro, test]
  input_type: ["graph"]
  max_atoms: 2000
  affine: false

model:
  name: fusion
  params:
    attention: false
    freeze: true
  first:
    name: sgcnn
    params:
      covalent_neighbor_threshold: 1.5
      non_covalent_neighbor_threshold: 4.5
      covalent_gather_width: 16
      covalent_k: 2
      non_covalent_gather_width: 12
      non_covalent_k: 2
    ckpt_path: "./results/MPRO/SGCNN-20230426-220143-9yu8ht5m-TRAIN80_FINETUNE/best_model.pth"
  second:
    name: efficientse3
    params:
      edge_dim: 16
      fiber_mid:
        0: 16
        1: 16
        2: 16
      out_multiplicity: 16
      num_convs: 3
      heads: 1
      dropout: 0.
      reduce_type: "edge"
      reduce_from: "ligand"
      pool_method: "add"
      x_ij: "add"
      pair_bias: true
      uniform_attention: true
      distance_cutoff: 5
    ckpt_path: "./results/MPRO/EFFICIENTSE3-20230717-014530-sxk7ievg-FINETUNEx0.5/best_model.pth"
  loss:
    - name: mse
      weight: 1.0

train:
  batch_size: 16
  num_workers: 8
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
