data:
  split:
    train:
      - [pdbbind2016, general]
      - [pdbbind2016, refined]
    val:
      - [pdbbind2016, core]
    test:
      - [pdbbind2016, core]
  preprocessing_type: processed # [raw, processed]
  feature_type: pybel # [pybel, rdkit]
  use_docking: false
  input_type: ["graph", "point"]
  max_atoms: 2000
  affine: false

model:
  name: fusion
  params:
    attention: false
    freeze: true
  first:
    name: sgcnn
    params:
      covalent_neighbor_threshold: 1.5
      non_covalent_neighbor_threshold: 4.5
      covalent_gather_width: 16
      covalent_k: 2
      non_covalent_gather_width: 12
      non_covalent_k: 2
    ckpt_path: "./results/PDBBIND2016/SGCNN-20230621-152625-19ssux38-GENERAL+REFINED/best_model.pth"
  second:
    name: pcn
    params:
      num_filters: 2048
      use_feat: false
    ckpt_path: "./results/PDBBIND2016/PCN-20230621-152516-33yfsvej-GENERAL+REFINED/best_model.pth"
  loss:
    - name: mse
      weight: 1.0

train:
  batch_size: 16
  num_workers: 8
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
