data:
  split:
    train:
      - [mpro, train]
      - [mpro, val]
    val:
      - [mpro, test]
    test:
      - [mpro, test]
  input_type: ["graph", "point"]
  max_atoms: 2000
  affine: false

model:
  name: fusion
  params:
    attention: false
    freeze: true
  first:
    name: pcn
    params:
      num_filters: 2048
      use_feat: false
    ckpt_path: ""
  second:
    name: efficientse3
    params:
      edge_dim: 16
      fiber_mid:
        0: 16
      out_multiplicity: 16
      num_convs: 3
      heads: 1
      dropout: 0.
      reduce_type: "edge"
      reduce_from: "ligand"
      pool_method: "add"
      x_ij: "add"
      pair_bias: true
      uniform_attention: true
      distance_cutoff: 5
  ckpt_path: "./SAVE_DIR/03142024/best_model.pth"
  loss:
    - name: mse
      weight: 1.0

train:
  batch_size: 16
  num_workers: 8
  epochs: 300
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 8
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
