data:
  name:
  split:
    train:
      - [pdbbind2020, train]
      - [pdbbind2020, val]
    val:
      - [pdbbind2020, test]
    test:
      - [pdbbind2020, test]
  feature_type: pybel # [pybel, rdkit]
  preprocessing_type: processed # [raw, processed]
  use_docking: false
  input_type: graph
  max_atoms: 2000

model:
  name: geomfusion
  params:
    estpose: True
  first:
    name: egnn
    params:
      in_edge_nf: 1
      distance_cutoff: 5
      n_layers: 6
      residual: True
      attention: True
      normalize: False
      tanh: False

  second:
    name: egnn
    params:
      in_edge_nf: 1
      distance_cutoff: 5
      n_layers: 6
      residual: True
      attention: True
      normalize: False
      tanh: False
    
  loss:
    - loss1: mse
      weight: 1.0
    - loss2: pmse
      weight: 1.0
  ckpt_path: ""

train:
  batch_size: 32
  num_workers: 8
  epochs: 200
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.001
  scheduler:
    name: multi_step
    params:
      milestones: [50, 100]
      gamma: 0.1

test:
  batch_size: 32
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
