data:
  name: pdbbind2020
  split:
    train:
      - train
    val:
      - val
    test:
      - test
  input_type: point
  affine: true
  max_atoms: 2000

model:
  name: pcn
  params:
    num_filters: 2048
    use_feat: false
    estlabel: true
    label_channels: 2
  loss:
    - name: ce
      weight: 1.0
    - name: mse
      weight: 1.0
  ckpt_path: ""

train:
  batch_size: 100
  epochs: 300
  num_workers: 0
  checkpoint_step: 100
  optimizer:
    name: adam # [sgd, rmsprop, adam]
    params:
      lr: 0.0001
  scheduler:
    name: multi_step
    params:
      milestones: [100, 200]
      gamma: 0.1

test:
  batch_size: 10
  checkpoint: best # [best, last]
  main_metric: rmse
  metrics:
    - rmse
    - mae
    - r2
    - pearson_r
    - spearman_r
